- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
OK - second attempt!
* Fixes #6
* Removed default 'Off' setting from the xVMHyper-V $State property
* Added check for $State property being set before calling Set-VMState
* Added Pester tests
> Fixes VM Power State Issue

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.schema.mof
- README.md
- Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
Adds support for setting SecureBoot on generation 2 virtual machines.
* Defaults to SecureBoot On ($true)
* SecureBoot setting Is ignored on generation 1 VMs
* Updated readme.md
* Adds test coverage for SecureBoot setting
> SecureBoot Implementation

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.schema.mof
- README.md
- Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
* Changes SwitchName to string[] to assign multiple NICs
* Changes MACAddress to string[] to specify multiple MAC addresses
* Updates test coverage
* Updates readme.md and adds multiple NIC example
* Fixes #33 
* Fixes #21
> xVMHyperV: Adds mulitple NIC and MAC address support

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.schema.mof
- DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1
- DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.schema.mof
- DSCResources/MSFT_xVhdFileDirectory/MSFT_xVhdFileDirectory.psm1
- README.md
- Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
- Tests/MSFT_xVMSwitch/xVMSwitch_BandwidthReservationMode.Tests.ps1
- appveyor.yml
- xHyper-V.psd1
> Release of version 3.3.0.0 of xHyper-V

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- README.md
- Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
* Fixes #28 
* Adds xVMHyperV localization support
* Updates readme.md
> Fixes xVMHyperV snapshot bug

- DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1
- README.md
- Tests/MSFT_xVMSwitch/xVMSwitch_BandwidthReservationMode.Tests.ps1
* Fixes #48
* Adds test to avoid regression
* Updates readme
> Fixes BandwidthReservationMode bug

- DSCResources/MSFT_xVHD/MSFT_xVHD.psm1
In reference to: #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/71)
> Changed property name in error mesage MaximumSizeBytes

- Examples/Sample_xVMHyperV_Complete.ps1
- Examples/Sample_xVMHyperV_DynamicMemory.ps1
- Examples/Sample_xVMHyperV_Simple.ps1
In reference to #36 Wrong value for 'Generation' field in Examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/70)
> Generation property changed to integer

- DSCResources/MSFT_xVHD/MSFT_xVHD.psm1
- Examples/Sample_xVMHyperV_Complete.ps1
- Examples/Sample_xVMHyperV_DynamicMemory.ps1
- Examples/Sample_xVMHyperV_Simple.ps1
- README.md
- appveyor.yml
- xHyper-V.psd1
Releasing version 3.6.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/74)
> Release of version 3.6.0.0 of xHyper-V

- README.md
- appveyor.yml
- xHyper-V.psd1
This should fix the tests in AppVeyor so that #79 can move forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/80)
> Revert Pester version and remove tabs

- DSCResources/HyperVCommon/HyperVCommon.psm1
- DSCResources/HyperVCommon/en-us/HyperVCommon.strings.psd1
- DSCResources/MSFT_xVMHost/MSFT_xVMHost.psm1
- DSCResources/MSFT_xVMHost/MSFT_xVMHost.schema.mof
- DSCResources/MSFT_xVMHost/en-US/MSFT_xVMHost.psd1
- README.md
- Tests/Integration/MSFT_xVMHost.Integration.Tests.ps1
- Tests/Integration/MSFT_xVMHost_set.config.ps1
- Tests/Unit/MSFT_xVMHost.tests.ps1
* Adds new xVMHost resource
* Adds unit and integration test coverage
* Updates Readme.md
* Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/88)
> Adds xVMHost resource

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- README.md
- Tests/Unit/MSFT_xVMHyperV.Tests.ps1
Fix for #76
Thanks @joeyaiello for your help at #83. I did not succeed on the rebase, as the conflicts where to complicated. But I simply made the few required changes to the latest code base. I hope all issues are now solved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/91)
> EnableGuestService localized OS fix 3

- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- README.md
- Tests/Unit/MSFT_xVMHyperV.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/100)
> fixes issues introduced with PR #91

- .vscode/settings.json
- README.md
Fixes #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/111)
> added vscode formatting settings Fixes #110

- .codecov.yml
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
- appveyor.yml
Updated appveyor.yml (include Codecov. Fixes #115 )
Added GitHub templates. Fixes: #103 
Added Codecov yml. Fixes #115
Added Codecov badges to Readme Fixes #115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/116)
> GitHub templates, Codecov, Appveyor updates

- Tests/Unit/MSFT_xVMDvdDrive.tests.ps1
Rushing this one through so that we can resolve issues with broken tests in other PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/139)
> Fixes for the breaking change in Pester v4

- CHANGELOG.md
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.schema.mof
- Examples/Sample_xVMHyperV_Complete.ps1
- Tests/Unit/MSFT_xVMHyperV.Tests.ps1
**Pull Request (PR) description**
Adds support for AutomaticCheckpoints of VMs as described in #130 
**This Pull Request (PR) fixes the following issues:**
Fixes #130
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/131)
> xVMHyperV - Added support for AutomaticCheckpointsEnabled

- CHANGELOG.md
- DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1
- DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.schema.mof
- DSCResources/MSFT_xVMSwitch/en-us/MSFT_xVMSwitch.strings.psd1
- Examples/Sample_xVMSwitch_ExternalSET_LBMode.ps1
- README.md
- Tests/Unit/MSFT_xVMSwitch_BandwidthReservationMode.Tests.ps1
- Tests/Unit/MSFT_xVMSwitch_EnableEmbeddedTeaming.Tests.ps1
**Pull Request (PR) description**
Added new parameter to specify the load balancing algorithm when Switch Embedded Teaming (SET) is used.
**This Pull Request (PR) fixes the following issues:**
Fixes #138
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/142)
> xVMSwitchFeature - load balancing algorithm parameter for SET Switch

- .vscode/settings.json
- CHANGELOG.md
- xHyper-V.psd1
Releasing version 3.12.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/151)
> Release of version 3.12.0.0 of xHyper-V

- .gitattributes
- .vscode/analyzersettings.psd1
- .vscode/settings.json
- CHANGELOG.md
- appveyor.yml
* Update appveyor.yml to use the default template.
* Added default template files .codecov.yml, .gitattributes, and .gitignore, and 
.vscode folder.
Entry should say what was changed, and how that affects users (if applicable).
and comment-based help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/156)
> Update to use template files

- CHANGELOG.md
- xHyper-V.psd1
Releasing version 3.15.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/164)
> Release of version 3.15.0.0 of xHyper-V

- CHANGELOG.md
- DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
- DSCResources/MSFT_xVMHyperV/en-US/MSFT_xVMHyperV.psd1
- xHyper-V.psd1
Releasing version 3.16.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xhyper-v/168)
> Release of version 3.16.0.0 of xHyper-V

- CHANGELOG.md
- Examples/Sample_xVMNetworkAdapter_MultipleVMMACAddress.ps1
- Examples/Sample_xVMNetworkAdapter_VMStaticNetworkSettings.ps1
- Examples/Sample_xVMNetworkAdapter_VMVlanTagging.ps1
Updated incorrect sample data for MacAddress
- Fixes #172 
Entry should say what was changed, and how that affects users (if applicable).
and comment-based help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xhyper-v/181)
> Fixed incorrect macaddress sample data

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xhyper-v/196)
> Deprecate module before rename

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/Problem_with_resource.yml
- CHANGELOG.md
- GitVersion.yml
- HISTORIC_CHANGELOG.md
- README.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
- source/HyperVDsc.psd1
- source/WikiSource/Home.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/hypervdsc/199)
> Updated pipeline files to support change of default branch to main

- CHANGELOG.md
- source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.psm1
- source/DSCResources/DSC_VMNetworkAdapter/DSC_VMNetworkAdapter.schema.mof
- source/Examples/Resources/VMNetworkAdapter/5-VMStaticNetworkSettings.ps1
- tests/Unit/DSC_VMNetworkAdapter.Tests.ps1
Fix some issues on NetworkSetting parameter
- Fixes #204
- Fixes #203
- Fixes #190
Entry should say what was changed and how that affects users (if applicable), and
reference the issue being resolved (if applicable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/hypervdsc/205)
> VMNetworkAdapter: fix some issues on NetworkSetting parameter
